### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rmanor/currentwidget#41]
```
Hi , I'm trying to build this using f-droid (FOSS repo and sdk frontend which 
uses platform tools v14 right now). Here is the setup:

Build 
Version:0.36b,31,r236,subdir=CurrentWidget,update=.;../CurrentWidgetLibrary,\
srclibs=Android-Color-Picker@1cc99729a82c,target=android-15,\
prebuild=echo "android.library.reference.1=../CurrentWidgetLibrary" > 
project.properties && \
echo "android.library.reference.1=$$Android-Color-Picker$$/AmbilWarna" >> 
project.properties && \
echo "target=android-8" > ../CurrentWidgetLibrary/project.properties && \
echo "target=android-8" >> project.properties


with the errors following,

/home/gerry/dalb8s-fdroiddata/build/com.manor.currentwidget/CurrentWidget/bin/An
droidManifest.xml:14: error: Error: No resource found that matches the given 
name (at 'label' with value '@string/app_name').
     [aapt] /home/gerry/dalb8s-fdroiddata/build/com.manor.currentwidget/CurrentWidget/bin/AndroidManifest.xml:14: error: Error: No resource found that matches the given name (at 'theme' with value '@style/MyTheme').
     [aapt] /home/gerry/dalb8s-fdroiddata/build/com.manor.currentwidget/CurrentWidget/bin/AndroidManifest.xml:25: error: Error: No resource found that matches the given name (at 'label' with value '@string/app_name').
     [aapt] /home/gerry/dalb8s-fdroiddata/build/com.manor.currentwidget/CurrentWidget/bin/AndroidManifest.xml:30: error: Error: No resource found that matches the given name (at 'resource' with value '@xml/current_widget_info').
     [aapt] /home/gerry/dalb8s-fdroiddata/build/com.manor.currentwidget/CurrentWidget/bin/AndroidManifest.xml:43: error: Error: No r

```

Original issue reported on code.google.com by `david8bl...@gmail.com` on 20 Sep 2012 at 6:26

**Comment by GoogleCodeExporter** [comment]
```
did you add  CurrentWidgetLibrary library project to the CurrentWidget project?
all those resources are in the library project.

```

Original comment by `ran.ma...@gmail.com` on 21 Sep 2012 at 1:48

**Comment by GoogleCodeExporter** [comment]
```
Ok , I added the Color-Picker library as a subproject to Current Widget 
Library, so the setup is:

Build 
Version:0.36b,31,236,subdir=CurrentWidget,update=.;../CurrentWidgetLibrary,\
srclibs=Color-Picker@5d697049fb,target=android-8,\
prebuild=echo "android.library.reference.1=../CurrentWidgetLibrary" >> 
project.properties && \
echo "android.library.reference.1=$$Color-Picker$$" >> 
../CurrentWidgetLibrary/project.properties

Now the error is  [aapt] 
/home/gerry/dalb8s-fdroiddata/build/com.manor.currentwidget/CurrentWidgetLibrary
/res/values-v11/theme.xml:3: error: Error retrieving parent for item: No 
resource found that matches the given name '@android:style/Theme.Holo'.
```

Original comment by `david8bl...@gmail.com` on 21 Sep 2012 at 9:07

**Comment by GoogleCodeExporter** [comment]
```
Build the library & app project with target api 15.
```

Original comment by `ran.ma...@gmail.com` on 22 Sep 2012 at 3:43

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Now I get: 


urrentwidget/library/CurrentWidget.java:526: cannot find symbol
    [javac] symbol  : variable icon
    [javac] location: class com.manor.currentwidget.library.R.drawable
    [javac]                         Notification notification = new Notification(R.drawable.icon,
    [javac]                                                                                ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /home/gerry/dalb8s-fdroiddata/build/com.manor.currentwidget/CurrentWidgetLibrary/src/com/manor/currentwidget/library/CurrentWidgetConfigure.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
==== stdout end ====
==== stderr begin ====

```

Original comment by `david8bl...@gmail.com` on 22 Sep 2012 at 9:30

**Comment by GoogleCodeExporter** [comment]
```
are you using Eclipse? 
it seems like you are trying to currentwidgetlibrary byitself and not as part 
of currentwidget..
try to copy icon.png from currentwidget to currentwidgetlibrary.. 
```

Original comment by `ran.ma...@gmail.com` on 22 Sep 2012 at 2:51

**Comment by GoogleCodeExporter** [comment]
```
No, f-droid uses ant. It is normally sufficient to reference a library by 
adding a line to the project.properties as I have done. After coopying across 
the icon I get this;

`dex] Converting compiled files and external libraries into 
/home/gerry/daithib8s-fdroiddata/build/com.manor.currentwidget/CurrentWidget/bin
/classes.dex...
       [dx] 
       [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] java.util.zip.ZipException: error in opening zip file
       [dx]     at java.util.zip.ZipFile.open(Native Method)
       [dx]     at java.util.zip.ZipFile.<init>(ZipFile.java:131)`
```

Original comment by `david8bl...@gmail.com` on 22 Sep 2012 at 3:07

**Comment by GoogleCodeExporter** [comment]
```
error opening zip? there are no zip files in the project..
```

Original comment by `ran.ma...@gmail.com` on 22 Sep 2012 at 3:33

**Comment by GoogleCodeExporter** [comment]
```
No but that error comes after the zipaligning happens. 
```

Original comment by `david8bl...@gmail.com` on 22 Sep 2012 at 3:43

**Comment by GoogleCodeExporter** [comment]
```
I suggest you first try to build the original project in eclipse and then move 
to ant.
```

Original comment by `ran.ma...@gmail.com` on 23 Sep 2012 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
There isn't much point since F-droid uses ant.
```

Original comment by `david8bl...@gmail.com` on 23 Sep 2012 at 4:02

**Comment by GoogleCodeExporter** [comment]
```
$ant release shouldn't zip align the apk anyway - that is done separately by 
zipalign.
```

Original comment by `david8bl...@gmail.com` on 23 Sep 2012 at 4:04

**Comment by GoogleCodeExporter** [comment]
```
$ant release shouldn't zip align the apk anyway - that is done separately by 
zipalign.
```

Original comment by `david8bl...@gmail.com` on 23 Sep 2012 at 4:04

**Comment by GoogleCodeExporter** [comment]
```
Can you get any better error decsription? it's hard to understand..
I think it would still be good to try with eclipse because it's easier to debug 
problems there.. we might see it fails there with the same problem.

check these links:
https://groups.google.com/forum/?fromgroups=#!topic/zxing/gfliICf9Tdw
https://groups.google.com/forum/?fromgroups=#!topic/android-building/0uo3f0fgD2c
https://www.google.com/search?sugexp=chrome,mod=15&sourceid=chrome&ie=UTF-8&q=ja
va.util.zip.ZipException%3A+error+in+opening+zip+file+dex
```

Original comment by `ran.ma...@gmail.com` on 24 Sep 2012 at 11:22
- Added labels: **Type-Task**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
My experience with these errors is that they are caused by duplication
```

Original comment by `david8bl...@gmail.com` on 14 Oct 2012 at 8:06

**Comment by GoogleCodeExporter** [comment]
```
I was able to fix this by adding android.library=true to the project.properties 
of CurrentWidgetLibrary. Seems fairly obvious , but I guess I didn't spot it 
because it is rare for a library not to have a project.properties. So this 
issue can be marked closed.
```

Original comment by `david8bl...@gmail.com` on 12 Jun 2013 at 11:11

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the update.
```

Original comment by `ran.ma...@gmail.com` on 12 Jun 2013 at 8:25
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
I added project.properties to the repository.
Btw, I'd be happy to get contributions if you make any interesting changes.
```

Original comment by `ran.ma...@gmail.com` on 14 Jun 2013 at 8:28
